"""Tests for generated-file detection.

Both directions matter: missing a minified bundle floods the results, and a
false positive silently hides code the user wrote by hand.
"""

from aetron.scanner.detect import generated_reason

HANDWRITTEN = "\n".join(f"def function_{i}():\n    return {i}\n" for i in range(50))


class TestNameMarkers:
    def test_minified_bundle(self):
        assert generated_reason("app.min.js", HANDWRITTEN) == "generated file name"

    def test_lock_file(self):
        assert generated_reason("package-lock.json", HANDWRITTEN) == "generated file name"

    def test_protobuf_output(self):
        assert generated_reason("service_pb2.py", HANDWRITTEN) == "generated file name"

    def test_plain_name_is_not_a_marker(self):
        assert generated_reason("minimap.py", HANDWRITTEN) is None


class TestBanners:
    def test_hash_comment_banner(self):
        text = "# Code generated by protoc. DO NOT EDIT.\nx = 1\n"
        assert generated_reason("api.py", text) == "generated header"

    def test_slash_comment_banner(self):
        text = "// <auto-generated />\nclass A {}\n"
        assert generated_reason("Api.cs", text) == "generated header"

    def test_marker_in_a_string_literal_is_not_a_banner(self):
        # detect.py itself failed this: its own marker list looked like a banner.
        text = 'MARKERS = (\n    "@generated",\n    "do not edit",\n)\n'
        assert generated_reason("detect.py", text) is None

    def test_marker_below_the_header_is_ignored(self):
        text = "\n".join(["x = 1"] * 30 + ["# do not edit"])
        assert generated_reason("module.py", text) is None


class TestMinification:
    def test_single_enormous_line_is_minified(self):
        assert generated_reason("bundle.js", "var a=1;" * 100_000) == "minified (long lines)"

    def test_large_handwritten_file_is_kept(self):
        # The case that motivated dropping size as a rejection reason: a real
        # module of about a megabyte must survive.
        text = "\n".join(f"CONSTANT_{i} = {i}" for i in range(60_000))
        assert len(text) > 1_000_000
        assert generated_reason("legacy.py", text) is None

    def test_short_file_with_one_long_line(self):
        assert generated_reason("data.py", "x = '" + "a" * 2000 + "'") is not None
