"""Heuristics for recognising machine-generated source files.

File size alone is a bad signal: a hand-written legacy module can be several
megabytes. Average line length separates real code (tens of characters) from
minified bundles (hundreds of thousands).
"""

GENERATED_NAME_MARKERS = (".min.", ".bundle.", ".generated.", "-lock.", "_pb2.")

GENERATED_HEADERS = (
    "@generated",
    "do not edit",
    "code generated by",
    "auto-generated",
    "autogenerated",
)

# A generated-file banner is always a comment in the first few lines. Requiring
# both keeps source that merely mentions these words from matching itself.
COMMENT_PREFIXES = ("#", "//", "/*", "*", "<!--", "--", ";")
HEADER_SCAN_LINES = 10

MAX_AVG_LINE_LENGTH = 500

# Not a heuristic, just a memory guard: never read a file larger than this.
HARD_SIZE_LIMIT = 20_000_000


def _has_generated_banner(text: str) -> bool:
    """True if one of the first lines is a comment marking the file generated."""
    for line in text.splitlines()[:HEADER_SCAN_LINES]:
        stripped = line.strip()
        if not stripped.startswith(COMMENT_PREFIXES):
            continue
        lowered = stripped.lower()
        if any(marker in lowered for marker in GENERATED_HEADERS):
            return True
    return False


def generated_reason(name: str, text: str) -> str | None:
    """Return why a file looks generated, or None if it looks hand-written."""
    lowered_name = name.lower()
    if any(marker in lowered_name for marker in GENERATED_NAME_MARKERS):
        return "generated file name"

    if _has_generated_banner(text):
        return "generated header"

    lines = text.count("\n") + 1
    if len(text) / lines > MAX_AVG_LINE_LENGTH:
        return "minified (long lines)"

    return None
