"""Heuristics for recognising machine-generated source files.

File size alone is a bad signal: a hand-written legacy module can be several
megabytes. Average line length separates real code (tens of characters) from
minified bundles (hundreds of thousands).
"""

GENERATED_NAME_MARKERS = (".min.", ".bundle.", ".generated.", "-lock.", "_pb2.")

GENERATED_HEADERS = (
    "@generated",
    "do not edit",
    "code generated by",
    "auto-generated",
    "autogenerated",
)

# A generated-file banner is always a comment in the first few lines. Requiring
# both keeps source that merely mentions these words from matching itself.
COMMENT_PREFIXES = ("#", "//", "/*", "*", "<!--", "--", ";")
HEADER_SCAN_LINES = 10

MAX_AVG_LINE_LENGTH = 500

# Not a heuristic, just a memory guard: never read a file larger than this.
HARD_SIZE_LIMIT = 20_000_000


def _has_generated_banner(text: str) -> bool:
    """True if one of the first lines is a comment marking the file generated."""
    for line in text.splitlines()[:HEADER_SCAN_LINES]:
        stripped = line.strip()
        if not stripped.startswith(COMMENT_PREFIXES):
            continue
        lowered = stripped.lower()
        if any(marker in lowered for marker in GENERATED_HEADERS):
            return True
    return False


# Editors on Windows - Visual Studio among them, by default - write a byte
# order mark at the start of a UTF-8 file. Decoding as plain "utf-8" leaves it
# in the text as U+FEFF, where Python's ast rejects it as a non-printable
# character and every C# pattern fails to match the first declaration. Reading
# as "utf-8-sig" removes it when present and is identical to "utf-8" when it is
# not. This matters more now that C# is parsed than it did before.
SOURCE_ENCODING = "utf-8-sig"


def read_source(path) -> str:
    """Read a source file the way every stage of Aetron should read one."""
    return path.read_text(encoding=SOURCE_ENCODING, errors="replace")


def count_lines(text: str) -> int:
    """How many lines a file has, the way every other tool counts them.

    A trailing newline ends the last line, it does not start another one, so
    "x = 1\n" is one line. Counting newlines and adding one made every file in
    the project one line longer than it is, which inflated every reported total
    and - worse - halved the average line length of a single-line file, letting
    minified files through the check below.

    Only "\n" separates lines here. str.splitlines is the obvious spelling and
    is wrong for this: it also breaks on form feed, vertical tab and U+2028,
    so a file using form feeds as page separators - ordinary in older C and
    Python - counted more lines than its parser sees, and every line number
    Aetron reports is only useful if it agrees with the parser.
    """
    return text.count("\n") + int(bool(text) and not text.endswith("\n"))


def generated_reason(name: str, text: str) -> str | None:
    """Return why a file looks generated, or None if it looks hand-written."""
    lowered_name = name.lower()
    if any(marker in lowered_name for marker in GENERATED_NAME_MARKERS):
        return "generated file name"

    if _has_generated_banner(text):
        return "generated header"

    lines = count_lines(text)
    if lines and len(text) / lines > MAX_AVG_LINE_LENGTH:
        return "minified (long lines)"

    return None
